### ISSUE TITLE
x1126 v2.35 client—As TS (Katy) I want to register in cassettes in the original sample processing registration page (manual and automatic) to allow for situations for when faculty have already printed off cassettes and part-processed the sample but we need to run them on the processing machines and embed them

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#527]
A message should appear to say this is registered in as tissue not original sample.

**Comment by KatyTudor** [comment]
@khelwood @seenanair @sabrine33 hi all, just testing this and the registration page works fine but when I came to section them I got the below error, I assume its because its not gone through the labware generation page, is there a way when registering the cassettes in they are default as a block or at the paraffin embedding operation to make them a block if they aren't already (i.e. for samples gone through the labware generation page)



![Image](https://github.com/sanger/stan-client/assets/111565178/13702efc-7d64-47c2-ba1d-ca13d7664587)

**Comment by KatyTudor** [comment]
@khelwood yes these a the odd occasion faculty had part processed them and printed cassettes but they aren't fully functioning blocks yet, they need to be put through the processing machine and embedded (which we document with the paraffin processing operation). Normally they would be registered on the original sample registration, then go to the labware generation - blocks operation (where the block change happens) then paraffin processed to embed them. This enhancement bypasses the middle step of the block operation

**Comment by khelwood** [comment]
@KatyTudor So if I understand, the paraffin processing op should turn any non-block into a block?

**Comment by KatyTudor** [comment]
@khelwood I think that would be the safest point for these type of "blocks" yes, the best point is in the lab generation page. So maybe the paraffin processing operation could convert to a block that isn't already a block?!

**Comment by khelwood** [comment]
@seenanair @KatyTudor  There is a pull request for the change to Paraffin processing https://github.com/sanger/stan-core/pull/336

**Comment by khelwood** [comment]
@KatyTudor I've updates UAT to make that change to paraffin processing

**Comment by KatyTudor** [comment]
@khelwood that has sorted it and working well, thanks for doing it so quickly
