### ISSUE TITLE
x1234—As ARA (Jasmine) I want to streamline the section planning labware creation, to help with mass section workflows

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#768]
Section planning.
Let people still use the page as it works now.
As an alternative, let people specify a labware type, number of labware and thickness, to add a bunch of such labware.
(They still go on to specify the contents of the labware as normal.)

**Comment by KatyTudor** [comment]
@sabrine33 
the drop downs look as I imaged however instead of making multiple separate labware it still clumps them into only being labware for one block so doesn’t save you anything (expect it pre-populates the thickness and labware). What I wanted this for was for when I am sectioning multiple different blocks. So, when I type in:
![Image](https://github.com/user-attachments/assets/cece27ff-e334-4729-ad07-17c3aea34d12)

 
It makes 5 lots of empty slides at 5um thick ready for 5 different blocks. Currently I would still have to make each different slide one by one.

**Comment by sabrine33** [comment]
@KatyTudor, thank you for the feedback, I will update it accordingly
